version: '3.4'

services:
  messagebroker:
    image: rabbitmq:management

  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: src/Products.API/Dockerfile
  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: src/Inventory.API/Dockerfile

